#pragma once

enum LIST_ERROR
{
    NO_ERROR = 0,
    NODE_ARRAY_NULL,
    OVERFLOW_NODE_ARRAY,
    NODE_PTR_NULL,
    LIST_PTR_NULL,
    NULL_FILE_PTR,
    NODE_UNALLOCATED,
    FILE_NOT_CLOSE,
    NODE_NOT_FOUND,
    INVALID_INDEX,
};

